---

- name: Update the web servers
  hosts: n1
  become: yes
  
  tasks:
  - name: Install pip on nodes
    apt:
      name: python3-pip
      state: present
    when: ansible_distribution == "CentOS"
      

...

